[tool.pylint]
# Configuration for Pylint

# Disable specific messages
disable = [
    "missing-docstring", # Disable missing docstring warnings
    "wrong-import-order",
    "wrong-import-position"
]

# Set the maximum number of characters on a single line
max-line-length = 100

# Set the maximum number of arguments for a function/method
max-args = 5

# Disable full report
reports = false
